// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Contra")]
[assembly: AssemblyProductAttribute("contra")]
[assembly: AssemblyDescriptionAttribute("A library providing a contravariant type mapping. Types can be registered against values, and lookup honours contravariance, message envelopes, etc. Useful for messaging.")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
