// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Contra")]
[assembly: AssemblyProductAttribute("contra")]
[assembly: AssemblyDescriptionAttribute("A library providing a contravariant type mapping. Types can be registered against values, and lookup honours contravariance, message envelopes, etc. Useful for messaging.")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
